# Generated by Django 5.1.7 on 2025-03-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('online_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Les groupes auxquels cet utilisateur appartient.', related_name='customuser_set', to='auth.group', verbose_name='groupes'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions spécifiques pour cet utilisateur.', related_name='customuser_set', to='auth.permission', verbose_name='permissions utilisateur'),
        ),
    ]
