# Generated by Django 5.1.7 on 2025-03-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('responsable_scolarite', 'Responsable Scolarité'), ('enseignant', 'Enseignant'), ('etudiant', 'Étudiant')], default='etudiant', max_length=25),
        ),
    ]
