# Generated by Django 5.1.5 on 2025-03-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0004_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='devoir_soumis',
            field=models.FileField(blank=True, null=True, upload_to='soumissions/'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='messages_forum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='quiz_reponses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
