# Generated by Django 5.1.7 on 2025-03-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0005_etudiant_devoir_soumis_etudiant_messages_forum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='devoir_soumis',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='messages_forum',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='quiz_reponses',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='score',
        ),
    ]
