# Generated by Django 5.1.7 on 2025-03-17 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0005_paiement_accountant_comptable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='accountant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_school.comptable'),
        ),
    ]
