# Generated by Django 5.1.7 on 2025-03-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0006_remove_etudiant_devoir_soumis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('responsable_scolarite', 'Responsable Scolarité')], default='etudiant', max_length=25),
        ),
    ]
