# Generated by Django 5.1.7 on 2025-03-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0007_alter_customuser_email_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='score_etudiant',
            field=models.IntegerField(default=0),
        ),
    ]
